mainsite/urls.py
from django.urls import path

from . import views

app_name = 'mainsite'
urlpatterns = [
	path('', views.landing, name='landing'),
	path('events', views.events, name='events'),
	path('reserve', views.reserve, name='reserve'),
	path('references', views.references, name='references'),
	path('tickets/<int:id>', views.tickets, name='tickets'),
	path(r'^pay/(?P<charge>\w+?)/$', views.pay.as_view(), name='pay'),
	path('charge/', views.charge, name='charge'),

]

speeddatingpainting/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from speeddatingpainting import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainsite.urls'))
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mainsite/models.py
from unittest.test.test_case import Test

from django.db import models

# Create your models here.
class Events(models.Model):
	name=models.CharField(max_length=100)
	date=models.DateTimeField(max_length=100)
	location=models.CharField(max_length=100)
	image=models.ImageField()
	description=models.CharField(max_length=100)
	price = models.IntegerField(null=True)

	def __str__(self):
		return self.name

	def formfield_for_foreignkey(self, db_field, request, **kwargs):
		if db_field.name == 'name':
			return Atendee(queryset=Test.objects.all())
		return super().formfield_for_foreignkey(db_field, request, **kwargs)


class Atendee(models.Model):
	MY_CHOICES = (
		('male','male'),
		('female','female'),
		('other','other'),
	)
	user_name=models.CharField(max_length=100)
	signup_date=models.DateTimeField(max_length=100)
	email=models.CharField(max_length=100)
	looking_for=models.CharField(max_length=100)
	age = models.IntegerField(null=True)
	gender = models.CharField(null=True, max_length=20, choices=MY_CHOICES)
	event = models.ForeignKey(Events, on_delete=models.CASCADE, null=True)
	phone_number = models.CharField(max_length=100, null=True)

	def __str__(self):
		return self.user_name

mainsite/forms.py
from django import forms
from django.http import request

from mainsite import models
from .models import Atendee


class AtendeeForm(forms.ModelForm):
    class Meta:
        model = Atendee
        fields = ['user_name', 'email','looking_for','age','gender','phone_number' ]

mainsite/views.py
from datetime import date

import urllib3
from django.core.mail import send_mail
from django.http import response
from django.http import request
from django.shortcuts import render, redirect
from django.urls import reverse
from urllib3.util import url

from mainsite.forms import AtendeeForm
from mainsite.models import Events, Atendee
from speeddatingpainting import settings
from django.views.generic.base import TemplateView
import stripe
from django.shortcuts import render
from django.conf import settings

stripe.api_key = settings.STRIPE_SECRET_KEY


def landing(response):
    return render(response, "landing.html")


def events(response):
    events =[]
    for event in Events.objects.all():
        name = event.name
        date = event.date
        location = event.location
        image = event.image
        description = event.description
        id = event.id
        one_event = {"name":name,"date":date,"location":location,"image":image,"decription":description,'id':id}
        events.append(one_event)

    return render(response, "events.html",{"events":events})


def reserve(response):
    return render(response, "reserve.html")


def references(response):
    return render(response, "references.html")

def tickets(request,id):
    if request.method == 'POST':
        form = AtendeeForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.signup_date = date.today()
            event = Events.objects.get(id=id).id
            event_price = Events.objects.get(id=id).price
            obj.event_id = event
            obj.save()
            men_number = Atendee.objects.filter(gender='male', event_id=id)
            woman_number = Atendee.objects.filter(gender='female', event_id=id)
            if obj.gender == 'male':
                if len(men_number) >= 10:
                    return render(request, "sorry.html")
                return redirect(reverse('mainsite:pay', kwargs={ 'charge': event_price }))
            else:
                if len(woman_number) >= 10:
                    return render(request, "sorry.html")
                return redirect(reverse('mainsite:pay', kwargs={ 'charge': event_price }))

    form = AtendeeForm()
    event = Events.objects.get(id=id)
    event_name = event.name
    event_date = event.date
    event_location = event.location
    event_price = event.price

    return render(request, "tickets.html", {"event_name":event_name, "event_date":event_date,'event_location':event_location, 'event_price':event_price, 'form':form },)


class pay(TemplateView):
    template_name = 'pay.html'
    def get_context_data(self, **kwargs):  # new
        context = super().get_context_data(**kwargs)
        context['key'] = settings.STRIPE_PUBLISHABLE_KEY
        context['charge']=self.kwargs['charge']
        return context

def charge(request):
    if request.method == 'POST':
        amount = request.POST.get('chargepass')
        charge = stripe.Charge.create(
            amount=amount,
            currency='usd',
            description='A Django charge',
            source=request.POST['stripeToken']
        )

        # here is where we also send if email..
        # make sure it only sends if payment goes through.... may need to pass through perameters to the f'n..
        mail_subject = 'See you soon!'
        message = 'we look forward to seeing you soon!'
        user_email = request.POST.get('stripeEmail')
        print(user_email)
        send_mail(
            mail_subject,
            message,
            'fridgeflipapp@gmail.com',
            [user_email],
            fail_silently=False,
        )


        return render(request, 'charge.html')

templates/base.html
{% load staticfiles %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <title>Dinosaur Dating</title>
</head>
<body>
<div id="wrapper">
    <nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active" aria-current="page">Dinosaur Dating</li>
  </ol>
</nav>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#"><img src={% static "images/logogrey.png" %} id="icon-img"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="{% url 'mainsite:landing' %}">What-we-do<span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="{% url 'mainsite:events' %}">Events</a>
      <a class="nav-item nav-link" href="{% url 'mainsite:references' %}">Recomendations</a>
    </div>
  </div>
</nav>

{% block content %}
{% endblock %}
</div>
</body>
</html>

templates/charge.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-1">
            </div>
            <div class="col-10">
<h1>thanks! you paid we look forward to hosting you.
    you should have been sent a confirmation email</h1>
               </div>
            <div class="col-1">
            </div>
        </div>
    </div>
{% endblock %}

templates/events.html
{% extends 'base.html' %}
{% block content %}
    <br>
    <div class="container" id ='eventcontainer'>
        <div class="row">
            <div class="col-12">

                <h1>all upcoming events</h1>
                {% for event in events %}
                    <div id="eventbox">
                        <img src="static/images/{{ event.image }}" id="event-image">

                        <h2 class="eventquestion">WHAT?</h2>
                        <h2> {{ event.name }}</h2>
                        <h2 class="eventquestion">WHEN?</h2>
                        <h2> {{ event.date }}</h2>
                        <h2 class="eventquestion">WHERE?</h2>
                        <h2> {{ event.location }}</h2>
                        <h2 class="eventquestion">HOW?</h2>
                        <p>{{ event.description }}</p>
                        <a  class='ticketbutton' href="/tickets/{{ event.id }}">Get tickets to {{ event.name }} </a>

                    </div>
                    <br>
                {% endfor %}
                <h1>past events</h1>
            </div>

        </div>

    </div>
{% endblock %}

templates/landing.html
{% extends 'base.html' %}
{% block content %}

{#                <img src="static/images/Dinosaur.png" id="logo">#}
{#        <br>#}
    <h1 id="landing_title">Dinosaur dating events</h1>
    <br>

    <br>
                <img src="static/images/Dinosaur-2_p001.png" id="event-image">
                 <img src="static/images/Dinosaur-3.png"id="event-image">

             <h2 id="speed-dating-tagline">We are changing the dating scene in TEl-AVIV.
                    We believe that getting out of your comfort zone and meeting people in real
                    life is a more enjoyable experience than online dating. We are giving you the
                    opportunity to experience a huge variety of creative dating events and meet all kinds of people
                    join us at our next event</h2>

    <a id="call-to-action" type="submit" href="{% url 'mainsite:events' %}">See our upcoming events!</a>

{% endblock %}

templates/pay.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-1">
            </div>
            <div class="col-10">
                <br>

                <h2>Purchase your ticket</h2>
                <h2>this event costs {{ charge }} NIS</h2>
<form action="{% url 'mainsite:charge' %}" method="post">
  {% csrf_token %}
    <input type="text" name="chargepass" value="{{ charge }}">
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="{{ key }}"
          data-description="{{ event.name }}"
          data-amount="{{ charge }}00"
          data-locale="auto"></script>
</form>
               </div>
            <div class="col-1">
            </div>
        </div>
    </div>
{% endblock %}

templates/references.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-1">
            </div>
            <div class="col-10">
                <h1>What people thought</h1>
                Oran:
                <h3>
                    "very professional, well spoken and has a lot to teach."</h3>
                Ron:
                <h3> "I've been at the speedate event, and it was awesome.
                    Oz is a kind person which it has been a pleasure to be hosted and guided by him.
                    And yes, I've been out with a date.
                    5/5!"
                </h3>
                Sandipan:
                <h3> "Had a super fun evening with Oz at his rooftop pairing session. Highly recommended!"</h3>

                Lola:
                <h3> "An amazing artist, professional, knowledgeable and talented. His art is the reflection of his patient personality, intelligent look and sensitive soul. I highly recommend him!"</h3>
            </div>
            <div class="col-1">
            </div>
        </div>
    </div>
{% endblock %}

templates/sorry.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-1">
            </div>
            <div class="col-10">
        <h1 class="sorrymessage">sorry but this event is full! We would
            love for you to join us though so take a
            look at all of our upcoming events!</h1>

                      <a class='seeotherevents' href="{% url 'mainsite:events' %}">See other events</a>

               </div>
            <div class="col-1">
            </div>
        </div>
    </div>
{% endblock %}

templates/tickets.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}
    <div class="container">
        <div class="row">
            <div class="col-1">
            </div>
            <div class="col-10">
                <br>
                <p>Sign up for {{ event_name }} on {{ event_date }} at {{ event_location }}
                    for {{ event_price }}NIS</p>
        <h1 class="filloutdetails">fill out some quick info before you pay so we can give you the best experience at our event! Click submit to go to our pay page</h1>
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <br>
                    <input type="submit" value="Submit" class="customfoodaddbutton" onclick="document.getElementsByClassName('stripe-button-el')[0].click()">
                </form>
                <br>
            </div>
            <div class="col-1">
            </div>
        </div>
    </div>



{% endblock %}